import barrel from './barrel.png'
import bench from './bench.png'
import carrot from './carrot-stages.png'
import farmhouse from './farmhouse.png'
import fence from './fence.png'
import flowerbox from './flowerbox.png'
import flowerpot from './flowerpot.png'
import iconBackup from './icon-backup.png'
import iconCodex from './icon-codex.png'
import iconDecorate from './icon-decorate.png'
import iconExperience from './icon-experience.png'
import iconHarvest from './icon-harvest.png'
import iconOrders from './icon-orders.png'
import iconReady from './icon-ready.png'
import iconSeeds from './icon-seeds.png'
import iconShop from './icon-shop.png'
import iconWarehouse from './icon-warehouse.png'
import iconWater from './icon-water.png'
import lantern from './lantern.png'
import mailbox from './mailbox.png'
import memorial from './memorial.png'
import potato from './potato-stages.png'
import pumpkin from './pumpkin-stages.png'
import scarecrow from './scarecrow.png'
import sign from './sign.png'
import strawberry from './strawberry-stages.png'
import tomato from './tomato-stages.png'
import tree from './tree.png'
import wheat from './wheat-stages.png'
import youmeiHarvest from './youmei-harvest.png'
import youmeiPlant from './youmei-plant.png'
import youmei from './youmei-sample.png'
import youmeiWalk from './youmei-walk.png'

export const cropSprites: Record<string, string> = { wheat, carrot, potato, tomato, strawberry, pumpkin }
export const decorationSprites: Record<string, string> = { barrel, flowerpot, fence, bench, scarecrow, sign, lantern, flowerbox, mailbox, memorial }
export const youmeiSprites = { idleAndWater: youmei, plant: youmeiPlant, harvest: youmeiHarvest, walk: youmeiWalk }
export const sceneSprites = { hut: farmhouse, tree }
export const toolSprites = { seeds: iconSeeds, water: iconWater, harvest: iconHarvest, orders: iconOrders, store: iconShop, decorate: iconDecorate, codex: iconCodex, backup: iconBackup }
export const statusSprites = { warehouse: iconWarehouse, experience: iconExperience, ready: iconReady }
