export const VERSION = '0.5.1'
export const SUPPORT_TTS_EXT_NAME = ['mp3', 'wav']
export const GET_BUFF_PROB_THROUGH_ACT = 0.2 // 通过活动获取buff的概率
export const GET_BUFF_NUM_THROUGH_ACT = 2 // 通过活动获取buff的数量
export const RETRY_TIMES_GET_BUFF_THROUGH_ACT = 3 // 重试获取buff的次数
export const MAX_WISHES_STORE_NUM = 30 // 最多保存几个愿望
export const WISH_GENERATE_INTERVAL = 2 * 60 * 60 * 1000 // 愿望生成间隔 - 2小时
// export const WISH_GENERATE_INTERVAL = 10 * 1000; // 愿望生成间隔，测试使用，3分钟
export const DAYS_TO_KEEP_WISH = 3 // 保留最近几天的愿望
export const PETMATE_ONLINE_DECAY_INTERVAL = 60 * 1000 // 在线属性衰减间隔 - 1分钟
export const PETMATE_ONLINE_DECAY_VALUE = 0 // 每次在线衰减的属性值
